// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// C:
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4L4K148OQAj5O8ASyKCRdkMuySszIDuU',
    appId: '1:805985234676:web:88c0d1f597251f84f8f8a1',
    messagingSenderId: '805985234676',
    projectId: 'bookhunters-dee9c',
    authDomain: 'bookhunters-dee9c.firebaseapp.com',
    storageBucket: 'bookhunters-dee9c.appspot.com',
    measurementId: 'G-SZ1Y9FX7S4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXfYW_kG_pu9uRE_VCBM5an541lLrbNnQ',
    appId: '1:805985234676:android:780558589df0d58ef8f8a1',
    messagingSenderId: '805985234676',
    projectId: 'bookhunters-dee9c',
    storageBucket: 'bookhunters-dee9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHDGwDfp_nA0aJ1iNDuahsZQX0jRZfhqw',
    appId: '1:805985234676:ios:18e10096c4eef995f8f8a1',
    messagingSenderId: '805985234676',
    projectId: 'bookhunters-dee9c',
    storageBucket: 'bookhunters-dee9c.appspot.com',
    iosBundleId: 'com.example.bookHunters',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHDGwDfp_nA0aJ1iNDuahsZQX0jRZfhqw',
    appId: '1:805985234676:ios:18e10096c4eef995f8f8a1',
    messagingSenderId: '805985234676',
    projectId: 'bookhunters-dee9c',
    storageBucket: 'bookhunters-dee9c.appspot.com',
    iosBundleId: 'com.example.bookHunters',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4L4K148OQAj5O8ASyKCRdkMuySszIDuU',
    appId: '1:805985234676:web:d678d3c71dcf6f78f8f8a1',
    messagingSenderId: '805985234676',
    projectId: 'bookhunters-dee9c',
    authDomain: 'bookhunters-dee9c.firebaseapp.com',
    storageBucket: 'bookhunters-dee9c.appspot.com',
    measurementId: 'G-J6DZZYW8LM',
  );
}
